version: '3'
networks:
  bridge:
    driver: bridge
services:
  db:
    image: postgres
    restart: "no"
    networks:
      - bridge
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./postgres/postgresql/:/var/lib/postgresql
      - ./postgres/data/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  sonarqube:
    image: sonarqube:8.9.0-community
    restart: "no"
    networks:
      - bridge
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - ./sonarqube/extensions/plugins/:/opt/sonarqube/extensions/plugins/
      - ./sonar/data/:/opt/sonarqube/data
      - ./sonar/logs/:/opt/sonarqube/logs
      - ./sonar/extensions/:/opt/sonarqube/extensions
      - ./sonar/conf/:/opt/sonarqube/conf
    depends_on:
      - db
    ports:
      - "9000:9000"